In [ ]:
%matplotlib inline


In [ ]:
from pylab import *
x = linspace(0, 5, 10)
y = x ** 2
figure()
plot(x, y, 'r')
xlabel('x')
ylabel('y')
title('title')
show()

In [ ]:
import numpy as np
b = np.array(range(0,3,1))
print("b:")
print(b)
c = np.array(range(5,8,1))
print("c:")
print(c)

cstack_bc = np.column_stack((b,c))
print("cstack_bc:")
print(cstack_bc)
rstack_bc = + np.hstack((b,c))
print("rstack_bc:")
print(rstack_bc)

In [ ]:
npr = np.r_[1:4,0,9]
print("npr:")
print(npr)
npc = np.c_[np.array([[1,2,3]]), 0, 0, np.array([[4,5,6]])]
print("npc:")
print(npc)

# broadcast
## 前提
* 执行的操作是element-wise的，因为只有这种按位操作才能容许矩阵size不匹配
* 当操作的是两个array时，numpy会比较它们的shape,其必须满足如下情况
  - 相等
  - 其中一个为1，（可以看做常数)  

## 目标  
   让不同shape的array能够进行数学运算


## 维度举例
   * 可以进行broadcase的维度  
     - 最后一维匹配  
  <pre><code>
    image (3d array): 256 x 256 x 3   
    cale  (1d array):             3  
    Result (3d array): 256 x 256 x 3 
 </pre></code> 
     - 任意一个维度为1（可扩展）  
  <pre><code>
	A      (4d array):  8 x 1 x 6 x 1  
		B      (3d array):      7 x 1 x 5  
		Result (4d array):  8 x 7 x 6 x 5  
 </pre></code> 
   * boardcast不能进行  
     - 一维矩阵维度不匹配  
  <pre><code>
		A      (1d array):  3  
		B      (1d array):  4 # trailing dimensions do not match  
 </pre></code> 
     - 第二维不匹配  
  <pre><code>
		A      (2d array):      2 x 1  
		B      (3d array):  8 x 4 x 3 # second from last dimensions mismatched   </pre></code> 

In [ ]:
import numpy as np

x = np.arange(4)
print("x:")
print(x)
xx = x.reshape(4, 1)
print("xx:")
print(xx)

y = np.ones(5)
print("y:")
print(y)
z = np.ones((3, 4))
print("z:")
print(z)

# 可行的broadcast操作
tmp = x + xx
print("x+xx:")
print(tmp)
tmp = x * xx
print("x*xx:")
print(tmp)
# error size
#x+y

# 可行的多维矩阵操作
print("x shape")
print(x.shape)
print("z shape")
print(z.shape)
tmp = x - z
print("x-z:")
print(tmp)



# Indexing操作技巧
  * 可以通过index返回值构建新的维度的数组
  * 多维数组的index默认取第一维
  * 可以给出多维的index，但是每个维度的index的size必须要一样

In [ ]:
import numpy as np

a = np.arange(12) ** 2  # 0到12 的平方构成的array
print("a:")
print(a)
i = np.array([1, 1, 3, 8, 5])  # index的array
print("a[i]:")
print(a[i])

j = np.array([[3, 4], [9, 7]])  # 多维索引
print("a[j]:")  # 返回的数组维度和索引数组的维度一样
print(a[j])

#设置一个调色盘
palette = np.array([[0, 0, 0],  # black
                    [255, 0, 0],  # red
                    [0, 255, 0],  # green
                    [0, 0, 255],  # blue
                    [255, 255, 255]])  # white
print("palette:")
print(palette)
#使用调色盘的颜色绘制一副简单的图像
image_idx = np.array([[0, 1, 2, 0],
                      [0, 3, 4, 0]])
print("image_idx:")
print(image_idx)

# 图像的size为 (2,4,3)
image = palette[image_idx]
print("image_shape:")
print(image.shape)
print("image:")
print(image)

##多维index例子
a = np.arange(12).reshape(3, 4)
print("a:")
print(a)

i = np.array([[0, 1],  # 索引a的第一维
              [1, 2]])
print("i:")
print(i)

j = np.array([[2, 1],  # 索引a的第二维
              [3, 3]])
print("j:")
print(j)

print("a[i]:")
print(a[i])

print("a[i，j]:")
print(a[i, j])  #i和j的维度要相同

print("a[i，2]:")
print(a[i, 2])

print("a[:]:")
print(a[:])
print("a[:,j]:")
print(a[:, j])

l = [i, j]  #也可以合并成一个数组取值,效果同a[i,j]
print("a[l]:")
print(a[l])

#注意不能把index的tuple作为array传入，这样会认为是要做第一维的索引
#s = np.array( [i,j] )
#a[s]

* 使用index解决时间序列的问题
  如何在有时序依赖的多维数据中找到最大值的问题

In [56]:
import numpy as np

time = np.linspace(20, 145, 5)  # 时间轴是一个5维的向量
print("time:")
print(time)

data = np.sin(np.arange(20)).reshape(5, 4)  # 时间轴上面抽样了4个序列
print("data:")
print(data)

ind = data.argmax(axis=0)  # 找到每个序列的最大值对应的index
print("ind:")
print(ind)

time_max = time[ind]  # 最大值对应的时间序列的值
print("time_max:")
print(time_max)

data_max = data[ind, range(data.shape[1])] #通过index取得每个序列的最大值成为一个向量,注意range的用法
print("data_max:")
print(data_max)

print("data_max==data.max(axit=0):")
print([data_max==data.max(axis=0)])
print("np.all(data_max == data.max(axis=0)")
print(np.all(data_max == data.max(axis=0)))


time:
[  20.     51.25   82.5   113.75  145.  ]
data:
[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
ind:
[2 0 3 1]
time_max:
[  82.5    20.    113.75   51.25]
data_max:
[ 0.98935825  0.84147098  0.99060736  0.6569866 ]
data_max==data.max(axit=0):
[array([ True,  True,  True,  True], dtype=bool)]
np.all(data_max == data.max(axis=0)
True
